/**
 * Initial Seed & Mock Fallback Data — SRS V6
 * Provides realistic initial data for offline / first-run demo state.
 */
import { Timestamp } from 'firebase/firestore';
import type { Tournament, Member, Finance, Match } from '../types';

export const INITIAL_SEED_MEMBERS: Member[] = [
  {
    id: 'mem_1',
    fullName: 'Trịnh Thị Hiền',
    gender: 'FEMALE',
    phone: '0912345678',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Ban Tổ Chức Hội Khóa K98-01',
    allTimeStats: {
      tournamentsPlayed: 3,
      matchesPlayed: 14,
      matchesWon: 11,
      pointsWon: 154,
      pointsLost: 98,
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_2',
    fullName: 'Lê Văn Hùng',
    gender: 'MALE',
    phone: '0987654321',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cây Vợt Vàng Yên Định 2',
    allTimeStats: {
      tournamentsPlayed: 4,
      matchesPlayed: 18,
      matchesWon: 15,
      pointsWon: 198,
      pointsLost: 120,
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_3',
    fullName: 'Nguyễn Thị Mai',
    gender: 'FEMALE',
    phone: '0903123456',
    school: 'YD3',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Đội trưởng Nữ K98-01',
    allTimeStats: {
      tournamentsPlayed: 2,
      matchesPlayed: 10,
      matchesWon: 8,
      pointsWon: 110,
      pointsLost: 75,
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_4',
    fullName: 'Trần Tuấn Anh',
    gender: 'MALE',
    phone: '0945678901',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'VĐV Tấn Công Xuất Sắc',
    allTimeStats: {
      tournamentsPlayed: 3,
      matchesPlayed: 12,
      matchesWon: 9,
      pointsWon: 132,
      pointsLost: 90,
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_5',
    fullName: 'Phạm Đức Cường',
    gender: 'MALE',
    phone: '0978901234',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Chuyên gia Đánh Lưới',
    allTimeStats: {
      tournamentsPlayed: 2,
      matchesPlayed: 8,
      matchesWon: 6,
      pointsWon: 88,
      pointsLost: 62,
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_6',
    fullName: 'Hoàng Thị Lan',
    gender: 'FEMALE',
    phone: '0967890123',
    school: 'YD3',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Tốc độ & Phòng thủ kiên cường',
    allTimeStats: {
      tournamentsPlayed: 2,
      matchesPlayed: 8,
      matchesWon: 5,
      pointsWon: 82,
      pointsLost: 70,
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];

export const INITIAL_SEED_TOURNAMENTS: Tournament[] = [
  {
    id: 'tour_2026_01',
    name: 'Giải Pickleball Mùa Xuân K98-01 Yên Định 2026',
    startDate: Timestamp.now(),
    status: 'ONGOING',
    publicSlug: 'giai-pickleball-mua-xuan-2026',
    createdBy: 'admin',
    config: {
      format: 'FIXED_DOUBLES',
      participants: { genderMode: 'MIXED', maxPlayers: 16 },
      rotating: {
        uniquePartnersRequired: 3,
        matchesRequiredPerPlayer: 'AUTO',
        maxPartnerRepeat: 1,
        balanceMatches: true,
        balanceRest: true,
        minimizeOpponentRepeat: true,
      },
      groups: { numberOfGroups: 2, maxEntitiesPerGroup: 4, assignmentMode: 'RANDOM' },
      scoring: { matchFormat: 'SINGLE_GAME', pointsToWin: 11, winByTwo: true, maxPoints: 15 },
      ranking: { rules: ['MATCH_WINS', 'POINT_DIFFERENCE', 'POINTS_WON', 'HEAD_TO_HEAD'] },
      knockout: { enabled: true, qualifiersPerGroup: 2, pairingMode: 'FIXED_BRACKET', drawMode: 'RANDOM' },
      scheduling: { courts: 2, restBetweenMatches: 5 },
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    completedAt: null,
  },
  {
    id: 'tour_2026_02',
    name: 'Giao Hữu Pickleball 3 Trường THPT Yên Định 1 - 2 - 3',
    startDate: Timestamp.now(),
    status: 'DRAWN',
    publicSlug: 'giao-huu-3-truong-yen-dinh-2026',
    createdBy: 'admin',
    config: {
      format: 'ROTATING_DOUBLES',
      participants: { genderMode: 'MIXED', maxPlayers: 12 },
      rotating: {
        uniquePartnersRequired: 3,
        matchesRequiredPerPlayer: 'AUTO',
        maxPartnerRepeat: 1,
        balanceMatches: true,
        balanceRest: true,
        minimizeOpponentRepeat: true,
      },
      groups: { numberOfGroups: 2, maxEntitiesPerGroup: 3, assignmentMode: 'RANDOM' },
      scoring: { matchFormat: 'SINGLE_GAME', pointsToWin: 11, winByTwo: true, maxPoints: 15 },
      ranking: { rules: ['MATCH_WINS', 'POINT_DIFFERENCE', 'POINTS_WON', 'HEAD_TO_HEAD'] },
      knockout: { enabled: true, qualifiersPerGroup: 2, pairingMode: 'FIXED_BRACKET', drawMode: 'RANDOM' },
      scheduling: { courts: 2, restBetweenMatches: 5 },
    },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
    completedAt: null,
  },
];

export const INITIAL_SEED_MATCHES: Record<string, Match[]> = {
  tour_2026_01: [
    {
      id: 'm_1',
      stage: 'GROUP',
      round: 1,
      groupId: 'A',
      courtId: 'Sân 1',
      order: 1,
      status: 'IN_PROGRESS',
      team1: {
        p1Id: 'mem_1',
        p1Name: 'Trịnh Thị Hiền',
        p2Id: 'mem_2',
        p2Name: 'Lê Văn Hùng',
      },
      team2: {
        p1Id: 'mem_3',
        p1Name: 'Nguyễn Thị Mai',
        p2Id: 'mem_4',
        p2Name: 'Trần Tuấn Anh',
      },
      games: [{ score1: 9, score2: 7 }],
      score1Total: 9,
      score2Total: 7,
      winner: 'NONE',
      operatorId: null,
      updatedAt: Timestamp.now(),
      completedAt: null,
    },
    {
      id: 'm_2',
      stage: 'GROUP',
      round: 1,
      groupId: 'B',
      courtId: 'Sân 2',
      order: 2,
      status: 'SCHEDULED',
      team1: {
        p1Id: 'mem_5',
        p1Name: 'Phạm Đức Cường',
        p2Id: 'mem_6',
        p2Name: 'Hoàng Thị Lan',
      },
      team2: {
        p1Id: 'mem_2',
        p1Name: 'Lê Văn Hùng',
        p2Id: 'mem_4',
        p2Name: 'Trần Tuấn Anh',
      },
      games: [{ score1: 0, score2: 0 }],
      score1Total: 0,
      score2Total: 0,
      winner: 'NONE',
      operatorId: null,
      updatedAt: Timestamp.now(),
      completedAt: null,
    },
  ],
};
