/**
 * Initial Seed & Mock Fallback Data — SRS V6
 * Provides realistic initial data for offline / first-run demo state.
 */
import { Timestamp } from 'firebase/firestore';
import type { Tournament, Member, Finance, Match } from '../types';

export const INITIAL_SEED_MEMBERS: Member[] = [
  {
    id: 'mem_01',
    fullName: 'Đỗ Bá Tùng',
    gender: 'MALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_02',
    fullName: 'Đỗ Bá Việt',
    gender: 'MALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_03',
    fullName: 'Lê Anh Tuấn',
    gender: 'MALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_04',
    fullName: 'Lê Thị Nga',
    gender: 'FEMALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_05',
    fullName: 'Lê Văn Sơn',
    gender: 'MALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_06',
    fullName: 'Nguyễn Anh Phúc',
    gender: 'MALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_07',
    fullName: 'Trịnh Hồng Xuân',
    gender: 'MALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_08',
    fullName: 'Vũ Ngọc Thuận',
    gender: 'MALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_09',
    fullName: 'Nguyễn Thị Hạnh',
    gender: 'FEMALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_10',
    fullName: 'Dương Văn Tĩnh',
    gender: 'MALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_11',
    fullName: 'Hoàng Anh Trung',
    gender: 'MALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_12',
    fullName: 'Nguyễn Sinh Thành',
    gender: 'MALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_13',
    fullName: 'Phan Văn Tuấn',
    gender: 'MALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_14',
    fullName: 'Trịnh Thị Hiền',
    gender: 'FEMALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_15',
    fullName: 'Trịnh Thị Mạnh',
    gender: 'FEMALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_16',
    fullName: 'Trịnh Thị Ngân',
    gender: 'FEMALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_17',
    fullName: 'Trịnh Văn Triệu',
    gender: 'MALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_18',
    fullName: 'Phạm Văn Huynh',
    gender: 'MALE',
    phone: '',
    school: 'YD3',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 3 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_19',
    fullName: 'Lê Minh Thảo',
    gender: 'MALE',
    phone: '',
    school: 'YD3',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 3 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_20',
    fullName: 'Đào Văn Chung',
    gender: 'MALE',
    phone: '',
    school: 'YD1',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 1 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_21',
    fullName: 'Lê Thị Thiện',
    gender: 'FEMALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_22',
    fullName: 'Phạm Thị Hoa',
    gender: 'FEMALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'mem_23',
    fullName: 'Trịnh Thị Luyến',
    gender: 'FEMALE',
    phone: '',
    school: 'YD2',
    avatarUrl: null,
    status: 'ACTIVE',
    note: 'Cựu học sinh THPT Yên Định 2 (K98-01)',
    allTimeStats: { tournamentsPlayed: 0, matchesPlayed: 0, matchesWon: 0, pointsWon: 0, pointsLost: 0 },
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];

export const INITIAL_SEED_TOURNAMENTS: Tournament[] = [];

export const INITIAL_SEED_MATCHES: Record<string, Match[]> = {};
